### ISSUE TITLE
ucenter 后台设置

### ISSUE THREAD

**Issue by dudubaba** [binaryoung/ucenter#1]
您好，请问ucenter 后台怎么设置？

**Comment by binaryoung** [comment]
在ucenter后台只需新建一个应用 并把应用页面填写的相关参数填入config文件或env文件

**Comment by dudubaba** [comment]
您好，应用的主URL填写哪个（http://mysite/xxx），才能通讯？xxx 填写啥，我试了好些，都不行

**Comment by binaryoung** [comment]
不填写 直接填写你laravel的根目录 比如你安装了这个插件的laravel地址是 http://www.a.com 那主目录就填http://www.a.com

**Comment by dudubaba** [comment]
return [
    'url'           => env('UC_URL', 'http://web.a.com'),
    'connect'        => env('UC_CONNECT', 'mysql'),
    'dbhost'        => env('UC_DBHOST', '192.168.1.254'),
    'dbuser'        => env('UC_DBUSER', 'admin'),
    'dbpw'            => env('UC_DBPW', 'admin'),
    'dbname'        => env('UC_DBNAME', 'vhall_bbs'),
    'dbcharset'    => env('UC_DBCHARSET', 'utf8'),
    'dbtablepre'    => env('UC_DBTABLEPRE', '`vhall_bbs`.pre_ucenter_'),
    'dbconnect'    => env('UC_DBCONNECT', '0'),
    'key'            => env('UC_KEY', '666cLXgFsrl6TcvDflhrvdcziY8SnhP1eexl1eQ'),
    'api'            => env('UC_API', 'http://bbs.a.com/uc_server'),
    'ip'            => env('UC_IP', '127.0.0.1'),
    'charset'        => env('UC_CHARSET', 'utf-8'),
    'appid'        => env('UC_APPID', '3'),
    'ppp'            => env('UC_PPP', '3'),
    'service'       =>  env('UC_SERVICE', 'Binaryoung\Ucenter\Services\Api'),
];

![Uploading QQ截图20150430124039.jpg…]()

**Comment by binaryoung** [comment]
ucenter的通讯机制是向填写的主URL+/api/uc.php 发送请求 这个插件的路由会响应 config里UC_URL值(默认为空)+/api/uc.php 也就是默认响应 网址+/api/uc.php

**Comment by dudubaba** [comment]
麻烦看下哪里有问题，通讯还是失败

**Comment by dudubaba** [comment]
url都是我本地虚拟主机

**Comment by dudubaba** [comment]
您好，加下我的QQ号：35626871

**Comment by binaryoung** [comment]
把UC_URL留为空 ucenter里面主URL设为可以访问到laravel的网址再试试

**Comment by dudubaba** [comment]
您好，已经这样设置了，还是不行
