### ISSUE TITLE
Laravel5.4 & Php7.1环境下按步骤安装后执行命令php artisan vendor:publish一直显示内存溢出

### ISSUE THREAD

**Issue by leochen41** [binaryoung/ucenter#10]
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 262144 bytes) in /laraveltest/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 549

**Comment by binaryoung** [comment]
能提供更详细的错误吗？
