### ISSUE TITLE
论坛ucenter后台通信失败问题

### ISSUE THREAD

**Issue by phgczm** [binaryoung/ucenter#2]
你好，楼主。我来laravel中安装了你的插件，通信原理是向我当前应用（laravel）的主URL+/api/uc.php 发送请求，但是我在laravel中需要定义路由器接受这个请求么？直接应用主URL+/api/uc.php不能访问吧？

请楼主指点

**Comment by binaryoung** [comment]
这个包已经定义了了这个路由并在Service Provider启动时加载了这个路由，具体可以查看https://github.com/binaryoung/ucenter/blob/master/src/routes.php#L3 所以不必再在laravel中定义此路由

**Comment by phgczm** [comment]
楼主你好，关了laravel的debugbar通信已经成功了。
1、但是还是不会使用这个扩展包，如果我不在laravel中不设置路由，就这个包的路由不能起作用（URL+api/uc.php不能访问）
2、本人初用laraval，楼主能否简单减少下扩展包是如何使用的？

**Comment by binaryoung** [comment]
1.在有些http服务器伪静态化没有设置好的情况下，http server会把uc.php当作php文件去解析就会出现错误，不知道你是不是这个问题。但是你又说通信成功，通信成功的话说明URL+api/uc.php说明可以访问呀。是否可以说的更详细点？
2.laravel的扩展包一般都是用composer require，然后添加 providers到laravel config，再设置facades。这是一般的使用办法。具体的还是要看具体的项目的github页面readme文档，应该会有很详细的安装，配置使用指导
任何问题欢迎随时提出：）

**Comment by phgczm** [comment]
感谢楼主，ucenter同步已经正常上线
