### ISSUE TITLE
同步更新data/cache/下面文件的时候 报错

### ISSUE THREAD

**Issue by willhope** [binaryoung/ucenter#4]
exception 'ErrorException' with message 'Undefined offset: 1' in /var/www/login/vendor/binaryoung/ucenter/src/uc_client/lib/xml.    对应的代码是：if(isset($attributes['id']) && !is_string($this->document[$attributes['id']])) {

**Comment by binaryoung** [comment]
package中提供的是默认api 我只是参照官方的例子，完成了api。更具体的api 业务逻辑需要自己重写api来实现。
