### ISSUE TITLE
composer update 报没有稳定的版本

### ISSUE THREAD

**Issue by phgczm** [binaryoung/ucenter#5]
composer.json的require中加入binaryoung/ucenter

在执行composer update进行更新得时候，报楼主的这个扩展包没有稳定的权限。

麻烦楼主查看下现在本扩展包能否正常使用

**Comment by binaryoung** [comment]
谢谢你的提醒。这个package一直处于开发阶段，所以并没有tag版本，导致composer无法update。最近正在重写，因为内置的ucenter官方api接口并不兼容php7。很快就会有稳定的版本。

**Comment by binaryoung** [comment]
发布了 `1.0.0` 版本
