### ISSUE TITLE
更新应用时 xml 解析错误

### ISSUE THREAD

**Issue by fuhaixiao** [binaryoung/ucenter#9]
错误堆栈：

[2017-01-12 02:25:18] production.ERROR: exception 'ErrorException' with message 'Undefined offset: 2' in /mnt/data/home/www/api17/shared/vendor/binaryoung/ucenter/src/uc_client/lib/xml.class.php:69
Stack trace:
#0 /mnt/data/home/www/api17/shared/vendor/binaryoung/ucenter/src/uc_client/lib/xml.class.php(69): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined offse...', '/mnt/data/home/...', 69, Array)
#1 [internal function]: XML->open(Resource id #9, 'item', Array)
#2 /mnt/data/home/www/api17/shared/vendor/binaryoung/ucenter/src/uc_client/lib/xml.class.php(62): xml_parse(Resource id #9, '<?xml version="...', 1)
#3 /mnt/data/home/www/api17/shared/vendor/binaryoung/ucenter/src/uc_client/lib/xml.class.php(12): XML->parse('<?xml version="...')
#4 /mnt/data/home/www/api17/shared/vendor/binaryoung/ucenter/src/Services/Help.php(80): xml_unserialize('<?xml version="...', 0)
#5 /mnt/data/home/www/api17/shared/vendor/binaryoung/ucenter/src/Controllers/ApiController.php(61): Binaryoung\Ucenter\Controllers\ApiController::unserialize('<?xml version="...')
#6 [internal function]: Binaryoung\Ucenter\Controllers\ApiController->run(Object(API17\Ucenter\Api))

**Comment by binaryoung** [comment]
请提供详细的运行环境
